# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

##########################################################
# Realizamos análisis de código estático con SonarCloud
##########################################################
- task: SonarCloudPrepare@1
  displayName: Configurar SonarCloud
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'devops-ort-g2'
    scannerMode: 'Other'
    projectKey: 'DevOps-ORT-G2_shipping-service'

- script: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=DevOps-ORT-G2_shipping-service
  displayName: 'Ejecutar análisis de SonarCloud'

- task: SonarCloudPublish@1
  displayName: Publicar resultado de análisis SonarCloud
  inputs:
    pollingTimeoutSec: '300'

##########################################################
# Chequear status del análisis de SonarCloud
# Si falló no continua el pipeline
##########################################################

- task: sonarcloud-buildbreaker@2
  displayName: Check PASSED SonarCloud 
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'devops-ort-g2'

##########################################################
# Buildeamos el JAR
##########################################################

#- script: mvn install
#  displayName: Generar build del jar

- task: Maven@4
  displayName: Generar build del jar
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

#################################################################################################
# Previo a crear la imagen de docker
# Aprovisionamos un api gateway para tener un unico punto de acceso para las pruebas postman
# Levantamos este docker primero para siempre tener misma IP y dejar seteado en postman
#################################################################################################

- script: |
    conf="upstream shipping {
      server 172.17.0.3:8080;
    }
    
    server {
      access_log /var/log/nginx/api_access.log main; # Each API may also log to a separate file
    
      listen 80;
      server_name _;
    
      location /shipping {
        proxy_pass http://shipping/shipping/;
      }
    }";
    docker pull nginx:1.21
    mkdir nginx-conf
    echo "$conf" > nginx-conf/api_gateway.conf
    cat nginx-conf/api_gateway.conf
    docker run --name api-gateway -v /home/vsts/work/1/s/nginx-conf/:/etc/nginx/conf.d/ -d nginx:1.21
    
  displayName: 'Aprovisionar API GATEWAY'

- script: docker inspect api-gateway | grep '"IPAddress":' -A 0 -m 1 | cut -f4 -d'"' 
  displayName: Consultar ip del docker api-gateway


#########################################################################################
# Buildeamos imagen docker del MS y levantamos para realizar pruebas con postman
#########################################################################################

- task: Docker@1
  displayName: Realizar build de imagen docker
  inputs:
    command: 'Build an image'
    dockerFile: '**/Dockerfile'
    arguments: '--build-arg JAR_FILE=target/shipping-service-example-0.0.1-SNAPSHOT.jar'
    imageName: 'shipping-service'

- script: docker run -d --name shipping-service-test shipping-service
  displayName: Levantar docker 

- script: docker inspect shipping-service-test | grep '"IPAddress":' -A 0 -m 1 | cut -f4 -d'"' 
  displayName: Obtener ip del docker MS

- script: docker ps -a
  displayName: Verificar dockers levantados

#########################################################################################
# Ejecutamos pruebas con newman desde un docker
#########################################################################################

- script: docker run -t postman/newman:alpine run "https://api.postman.com/collections/7660732-a08b303d-8652-4454-b982-33255a844916?access_key=PMAT-01GK3877AHTJJ4R6ESMFJ6M6VP" 
  displayName: Ejecutar test Postman
    
##########################################################
# Pusheamos la imagen de docker al ECR
##########################################################
#- task: ECRPushImage@1
#  inputs:
#    awsCredentials: 'AWS'
#    regionName: 'us-east-1'
#    imageSource: 'imagename'
#    sourceImageName: 'shipping-service'
#    repositoryName: 'shipping-service'
    